# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViT4MNIST' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViT4MNIST
  pod 'LibTorch-Lite', '~>1.9.0'
end
