# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpeechRecognition' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpeechRecognition
  pod 'LibTorch-Lite', '~>1.9.0'
end
