# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'D2Go' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for D2Go
  pod 'vision-nightly'

end
