# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StreamingASR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StreamingASR
  pod 'LibTorch-Lite', '~>1.11.0'
  pod 'RosaKit'
end
